# Overton API configuration

# API credentials
api_key: ${OVERTON_API_KEY}

# API endpoints
base_url: https://app.overton.io/
documents_url: https://app.overton.io/documents.php

# Request parameters
default_parameters:
  format: json

# Query options
query:
  max_results: 10000  # Maximum results to retrieve per query
  default_fields:
    - id
    - title
    - source
    - published_date
    - url
    - type
    - geography
    - mentions

# Rate limiting
rate_limits:
  requests_per_second: 1
  max_requests_per_minute: 60
  
# Retry configuration
retries:
  max_attempts: 3
  backoff_factor: 2
  status_forcelist: [429, 500, 502, 503, 504]
  
# Pagination
pagination:
  items_per_page: 100
  
# Cache configuration
cache:
  enabled: true
  expiration: 86400  # seconds (24 hours)
  directory: ./data/cache/overton
